# Generated by Django 5.1.6 on 2025-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingdetails',
            name='before_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
