# Generated by Django 5.1.6 on 2025-02-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0002_weddingdetails_before_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingdetails',
            name='after_date',
        ),
        migrations.RemoveField(
            model_name='weddingdetails',
            name='before_date',
        ),
        migrations.RemoveField(
            model_name='weddingdetails',
            name='before_time',
        ),
    ]
