# Generated by Django 5.1.6 on 2025-02-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0003_remove_weddingdetails_after_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
