# Generated by Django 5.1.6 on 2025-02-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0006_alter_rsvp_guest_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('messages', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='media',
            name='slide2',
        ),
        migrations.RemoveField(
            model_name='media',
            name='slide3',
        ),
        migrations.RemoveField(
            model_name='media',
            name='slide4',
        ),
    ]
