# Generated by Django 5.1.6 on 2025-02-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0007_message_remove_media_slide2_remove_media_slide3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messages',
            new_name='text',
        ),
    ]
