# Generated by Django 5.1.6 on 2025-02-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0008_rename_messages_message_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
