# Generated by Django 5.1.6 on 2025-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0010_remove_rsvp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
