# Generated by Django 5.1.6 on 2025-02-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0011_message_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='slide1',
            new_name='bride',
        ),
        migrations.AddField(
            model_name='media',
            name='bride_n_groom',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='media',
            name='groom',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
