# Generated by Django 5.1.6 on 2025-02-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0012_rename_slide1_media_bride_media_bride_n_groom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
