# Generated by Django 5.1.6 on 2025-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WedApp', '0013_message_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingdetails',
            old_name='phone_number',
            new_name='bride_phone_number',
        ),
        migrations.RemoveField(
            model_name='weddingdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='weddingdetails',
            name='groom_phone_number',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
